### ISSUE TITLE
Please add pandas in requirements.txt

### ISSUE THREAD

**Issue by hritwikk** [ramsrigouthamg/Questgen.ai#2]
Hello, It seems pandas is required by "Questgen/mcq/mcq.py" please add if that's required or some bug.

**(venv) gdev@GDevs-iMac gen_q % python test.py
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    from Questgen import main
  File "/Users/gdev/PycharmProjects/gen_q_2/venv/lib/python3.7/site-packages/Questgen/__init__.py", line 4, in <module>
    from Questgen.mcq import mcq
  File "/Users/gdev/PycharmProjects/gen_q_2/venv/lib/python3.7/site-packages/Questgen/mcq/mcq.py", line 2, in <module>
    import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
ModuleNotFoundError: No module named 'pandas'**

Thanks

**Comment by ramsrigouthamg** [comment]
@hritwikk We shall look into it. Thanks for letting us know.

**Comment by parthplc** [comment]
Added pandas into requirement.txt.
